### ISSUE TITLE
Vue3风格统一认领：选项式升级成组合式API

### ISSUE THREAD

**Issue by sudoooooo** [didi/xiaoju-survey#108]
由于工程是从vue2升级到vue3，目前项目里还保留了大部分选项式API的写法：[升级文档]()。
如果你想**熟悉工程和组合式API写法**，或者**参与贡献**，这是一个比较好的机会。

## 认领方式
> 为保障正常建设，认领1个月内无响应(沟通讨论/技术方案/PR)，任务自动释放

1、**留言认领文件以免重复建设**
2、改造后通过以下检测：
- vscode无飘红（安装插件：[Vue - Official](https://cn.vuejs.org/guide/scaling-up/tooling.html#ide-support) 和 Eslint）
- npm run format
- npm run lint
- 相关功能自测通过

3、提交PR到develop分支

## List
升级完成：
@alwayrun [refactor: 重构 render/pages 目录下三个文件, 使用 Vue3 组合式 API 写法](https://github.com/didi/xiaoju-survey/commit/f9af6219abd26071eee72a335d220675c3474d10)
@alwayrun [refactor: 重构 render/App.vue, 使用 Vue3 组合式 API 写法](https://github.com/didi/xiaoju-survey/commit/65884f80f661daeac325f8c8b2e4e546c07add14)
@alwayrun [refactor: 重构 render/components 目录下部分组件, 使用 Vue3 组合式 API 写法](https://github.com/didi/xiaoju-survey/commit/5e50a3a73301dd5290c249b2028d52721c57ba7a)
@alwayrun [refactor: 重构 materials/setters/widgets 目录下部分组件, 使用 Vue3 组合式 API 写法](https://github.com/didi/xiaoju-survey/commit/6c9044b457bf6941b62c5837a9701b90bce44a77)
@alwayrun [refactor: 重构 management/components 目录下组件, 使用 Vue3 组合式 API 写法](https://github.com/didi/xiaoju-survey/commit/3242ad80c4ecae11655c70b5c5e388464d7fd03a)
@1004801012 [refactor: Vue3 组合式 API 写法重构](https://github.com/didi/xiaoju-survey/commit/89d416becd2b38f7001bd52912b5269b556c2362)
@alwayrun [refactor: 重构 management/pages/publishResult 目录下组件, 使用 Vue3 组合式 API 写法](https://github.com/didi/xiaoju-survey/commit/fd6585d80cbff6a0b6dcd6f92d07f01a3a940f14)
@Codeniu [refactor: 使用vue3组合式API重构登录页代码](https://github.com/didi/xiaoju-survey/commit/dc7542de60bece8d40cc16ec9920b756f53374da)
@chaorenluo [refactor: questionModule/PreviewPanel.vue和skin/PreviewPanel.vue 重构](https://github.com/didi/xiaoju-survey/commit/5f8896eec2f523f351e5d72a73d64fc7269d4f45#diff-5883d7d85ed246b71f69ee1594f26eb14a739eb12edbd38641edfcc604d7027c)
@skique [feat: 问卷空间协作能力前端](https://github.com/didi/xiaoju-survey/commit/7ad01f6b26865364fb65838a736800561df30edd#diff-dc89c712925852efacaa9c30fc8d118cf9a2dc5028467c1b9fd7055c409a5277)
@alwayrun [refactor: 重构 management/pages/edit 目录下组件, 使用 Vue3 组合式 API 写法](https://github.com/didi/xiaoju-survey/commit/cffe037269e5d5f8e4e8ca95141320b16c5b6021)
@Realabiha https://github.com/didi/xiaoju-survey/issues/108#issuecomment-2114840813

**Comment by alwayrun** [comment]
我来试着领一个试试
文件： render/pages/SuccessPage.vue

**Comment by alwayrun** [comment]
使用 Vue3 组合式 API 写法, 重构下例三个文件
render/pages/ErrorPage.vue
render/pages/IndexPage.vue
render/pages/SuccessPage.vue

@sudoooooo

**Comment by sudoooooo** [comment]
> 使用 Vue3 组合式 API 写法, 重构下例三个文件 render/pages/ErrorPage.vue render/pages/IndexPage.vue render/pages/SuccessPage.vue
> 
> @sudoooooo

好的，升级后提PR即可

**Comment by alwayrun** [comment]
使用 Vue3 组合式 API 写法对 render/components 目录列表文件进行调整

```bash
render
├── components                                                
│   ├── AlertDialog.vue
│   ├── ConfirmDialog.vue
│   ├── HeaderSetter.vue
│   ├── LogoIcon.vue
│   ├── MainRenderer.vue
│   ├── MainTitle.vue
│   ├── SubmitSetter.vue

@sudoooooo

**Comment by Realabiha** [comment]
认领重构下列两个文件
render/pages/EmptyPage.vue
management/components/EmptyIndex.vue

**Comment by sudoooooo** [comment]
> 使用 Vue3 组合式 API 写法对 render/components 目录列表文件进行调整
> 
> ```shell
> render
> ├── components                                                
> │   ├── AlertDialog.vue
> │   ├── ConfirmDialog.vue
> │   ├── HeaderSetter.vue
> │   ├── LogoIcon.vue
> │   ├── MainRenderer.vue
> │   ├── MainTitle.vue
> │   ├── SubmitSetter.vue
> ```
> 
> @sudoooooo

@alwayrun 这部分内容已CR，已备注有功能失效了，请查看下

**Comment by alwayrun** [comment]
> @alwayrun 这部分内容已CR，已备注有功能失效了，请查看下

@sudoooooo  已解决， 你再查看下还有没有问题

**Comment by sudoooooo** [comment]
> > @alwayrun 这部分内容已CR，已备注有功能失效了，请查看下
> 
> @sudoooooo 已解决

hai

**Comment by sudoooooo** [comment]
> > @alwayrun 这部分内容已CR，已备注有功能失效了，请查看下
> 
> @sudoooooo 已解决

@alwayrun  banner链接依然有问题，已截图备注，请查看下

**Comment by alwayrun** [comment]
> @alwayrun banner链接依然有问题，已截图备注，请查看下

还是想同的问题吗？我这边只看到你之前截图备注，我目前测试是可以的
设置 banner链接相关值信息:
<img width="727" alt="image" src="https://github.com/didi/xiaoju-survey/assets/558808/84bb2623-142b-4841-b65b-99030aba8679">

条件检测已跳过到 window.open 所在行:
<img width="955" alt="image" src="https://github.com/didi/xiaoju-survey/assets/558808/627d86ea-062c-4bd8-b2ad-e03d62138b93">

**Comment by alwayrun** [comment]
> @alwayrun banner链接依然有问题，已截图备注，请查看下

还是想同的问题吗？我这边只看到你之前截图备注，我目前测试是可以的
设置 banner链接相关值信息:
<img width="727" alt="image" src="https://github.com/didi/xiaoju-survey/assets/558808/84bb2623-142b-4841-b65b-99030aba8679">

条件检测已跳过到 window.open 所在行:
<img width="955" alt="image" src="https://github.com/didi/xiaoju-survey/assets/558808/627d86ea-062c-4bd8-b2ad-e03d62138b93">

**Comment by alwayrun** [comment]
@sudoooooo  

setters/widgets/FreqAndNumberLimit.vue 这个组件目前没查到使用他的地方，这个组件主要是用做啥限制的，或者给我一段设置属性中的配置信息，我附加到某个组件中测试一下

**Comment by sudoooooo** [comment]
> @sudoooooo
> 
> setters/widgets/FreqAndNumberLimit.vue 这个组件目前没查到使用他的地方，这个组件主要是用做啥限制的，或者给我一段设置属性中的配置信息，我附加到某个组件中测试一下

@alwayrun 次数限制的setter，后续会在问卷设置用到，改后提交即可，用到的时候再验证。

**Comment by 1004801012** [comment]
认领重构下列三个文件

management/pages/create/components/CreateForm.vue
management/pages/create/components/NavHeader.vue
management/pages/create/components/TypeList.vue
management/pages/create/CreatePage.vue

**Comment by alwayrun** [comment]
使用 Vue3 组合式 API 写法对 management/components 目录列表文件进行调整

```bash
management                                        
│   ├── components
│   │   ├── EmptyIndex.vue
│   │   ├── LeftMenu.vue
│   │   └── LogoIcon.vue
```

@sudoooooo

**Comment by alwayrun** [comment]
使用 Vue3 组合式 API 写法对 management/pages/publishResult 目录列表文件进行调整

```bash
management/pages/publishResult
├── PublishResultPage.vue
└── components
    ├── ChannelRow.vue
    └── QRCode.vue
```

@sudoooooo

**Comment by Codeniu** [comment]
认领登录页代码风格统一：
web\src\management\pages\login\LoginPage.vue

**Comment by alwayrun** [comment]
使用 Vue3 组合式 API 写法对 management/pages/edit 目录列表文件进行调整

```bash
src/management/pages/edit
├── components
│   ├── LogoPreview.vue
│   ├── MainTitle.vue
│   ├── ModuleNavbar.vue
│   ├── SetterField.vue
│   └── SubmitButton.vue
├── index.vue
├── modules
│   ├── contentModule
│   │   ├── HistoryPanel.vue
│   │   ├── PublishPanel.vue
│   │   └── SavePanel.vue
│   ├── generalModule
│   │   ├── BackPanel.vue
│   │   ├── NavPanel.vue
│   │   └── TitlePanel.vue
│   ├── questionModule
│   │   ├── CatalogPanel.vue
│   │   ├── PreviewPanel.vue
│   │   ├── SetterPanel.vue
│   │   └── components
│   │       ├── CatalogItem.vue
│   │       └── QuestionCatalog.vue
│   └── settingModule
│       ├── SettingPanel.vue
│       ├── components
│       │   ├── BannerContent.vue
│       │   ├── OverTime.vue
│       │   └── SuccessContent.vue
│       ├── result
│       │   ├── CatalogPanel.vue
│       │   ├── PreviewPanel.vue
│       │   └── SetterPanel.vue
│       └── skin
│           ├── CatalogPanel.vue
│           ├── PreviewPanel.vue
│           └── SetterPanel.vue
└── pages
    ├── edit
    │   ├── QuestionEditPage.vue
    │   └── index.vue
    ├── setting
    │   └── index.vue
    └── skin
        ├── ContentPage.vue
        ├── ResultPage.vue
        └── index.vue
```

@sudoooooo

**Comment by sudoooooo** [comment]
> 使用 Vue3 组合式 API 写法对 management/pages/edit 目录列表文件进行调整
> 
> ```shell
> src/management/pages/edit
> ├── components
> │   ├── LogoPreview.vue
> │   ├── MainTitle.vue
> │   ├── ModuleNavbar.vue
> │   ├── SetterField.vue
> │   └── SubmitButton.vue
> ├── index.vue
> ├── modules
> │   ├── contentModule
> │   │   ├── HistoryPanel.vue
> │   │   ├── PublishPanel.vue
> │   │   └── SavePanel.vue
> │   ├── generalModule
> │   │   ├── BackPanel.vue
> │   │   ├── NavPanel.vue
> │   │   └── TitlePanel.vue
> │   ├── questionModule
> │   │   ├── CatalogPanel.vue
> │   │   ├── SetterPanel.vue
> │   │   └── components
> │   │       ├── CatalogItem.vue
> │   │       └── QuestionCatalog.vue
> │   └── settingModule
> │       ├── SettingPanel.vue
> │       ├── components
> │       │   ├── BannerContent.vue
> │       │   ├── OverTime.vue
> │       │   └── SuccessContent.vue
> │       ├── result
> │       │   ├── CatalogPanel.vue
> │       │   ├── PreviewPanel.vue
> │       │   └── SetterPanel.vue
> │       └── skin
> │           ├── CatalogPanel.vue
> │           └── SetterPanel.vue
> └── pages
>     ├── edit
>     │   ├── QuestionEditPage.vue
>     │   └── index.vue
>     ├── setting
>     │   └── index.vue
>     └── skin
>         ├── ContentPage.vue
>         ├── ResultPage.vue
>         └── index.vue
> ```
> 
> @sudoooooo

@alwayrun 👍～ 头图、提示语、按钮和logo在渲染统一里做了调整，收拢到了物料里面，目前正在CR，优化过后就合并，所以这几个文件可以跳过：
https://github.com/didi/xiaoju-survey/pull/168

**Comment by skique** [comment]
认领重构下列组件, 调整成 Vue3 组合式 API 写法
management/pages/list/components/BaseList.vue
management/pages/list/components/ModifyDialog.vue
management/pages/list/index.vue.vue
management/pages/list/components/ToolBar.vue
management/pages/list/components/TextSelect.vue
management/pages/list/components/TextButton.vue.vue
