### ISSUE TITLE
最后一题活动状态下删除操作会触发两处问题

### ISSUE THREAD

**Issue by alwayrun** [didi/xiaoju-survey#140]
### 分类
前端

### 系统
Mac

### 复现步骤
当前题型在活动状态且是最后一个题型时删除会触发两处问题
1:  当删除操作发生时，当前题型已不再是活动题型，所以侧边题型属性设置域区要消失
2、由于侧边题型属性设置域区未消失，会导致 Setter 部分组件依赖于 modelConfig 内部组件出错

准备操作前展示如下：
<img width="1406" alt="image" src="https://github.com/didi/xiaoju-survey/assets/558808/1948ee73-4185-48c7-a0b5-4832bf4ffd36">

操作完成后如下:
<img width="1433" alt="image" src="https://github.com/didi/xiaoju-survey/assets/558808/3aa1dd16-ed29-47d2-9206-f4866b32dec9">

**Comment by sudoooooo** [comment]
fix已合并: https://github.com/didi/xiaoju-survey/commit/ac33ffa34a4fcf56bafeae5f6c3bb277ad288bfd
