### ISSUE TITLE
题型处于活动选区状态下，反复点击多一直触发 select 事件

### ISSUE THREAD

**Issue by alwayrun** [didi/xiaoju-survey#154]
### 分类
前端

### 系统
mac
### 复现步骤
题型处于活动选区状态下，反复点击当前题型所在区域会一直触发 select 事件
这不合理，select 事件只在题型切换时才触发

测试代码如下:
<img width="978" alt="image" src="https://github.com/didi/xiaoju-survey/assets/558808/85b4ac0f-7e43-4ed7-9045-f4f3036d8bd3">

执行结果如下:
<img width="1127" alt="image" src="https://github.com/didi/xiaoju-survey/assets/558808/c8a9f3fd-8f9e-4457-a5d9-106f1936f0f5">

**Comment by sudoooooo** [comment]
感谢反馈和修复，已合并：https://github.com/didi/xiaoju-survey/commit/24881d7cdcd2f6cf42ac4355eda8449733676995
