### ISSUE TITLE
题型处于活动状态时，侧边操作工具栏默认显示

### ISSUE THREAD

**Issue by alwayrun** [didi/xiaoju-survey#156]
### 描述您希望的需求
当前题型处于活动状态时，侧边操作栏应处于显示状态，这样不管光标移动到何处，再次移回时不需要先移动到活动题选区，而是可直接到活动题型侧边栏做相应操作，

所以在以下两种状态下显示侧边操栏较合理:
1、光标所在区题型 _（不一定是活动题型）_
2、活动区题型 _（光标不一定在活动题选区）_

**Comment by sudoooooo** [comment]
@alwayrun 可以提升操作时的体验 👍
