### ISSUE TITLE
问卷配置题型标题栏编辑框无法失去焦点问题

### ISSUE THREAD

**Issue by alwayrun** [didi/xiaoju-survey#161]
### 分类
前端

### 系统
mac
### 复现步骤
1、点击题目标题进入可编辑模式, 编辑完成后
2、点击背景高亮区域任何地方都无法让标题编辑框失去焦点
3、正常交互流程应该是点击非标题编辑框以外的任何地方都应该使其失去焦点

<img width="1327" alt="image" src="https://github.com/didi/xiaoju-survey/assets/558808/aea1a886-7e80-43b8-8837-edadc6c32aa7">

**Comment by sudoooooo** [comment]
选项类似

**Comment by alwayrun** [comment]
> 选项类似

@sudoooooo  所有题型都有类似问题

**Comment by sudoooooo** [comment]
已收录进优化： https://github.com/didi/xiaoju-survey/issues/182 第4项，欢迎大家认领

**Comment by sudoooooo** [comment]
> 已收录进优化： #182 第4项，欢迎大家认领

@alwayrun 已完成优化，关闭issue，欢迎更多反馈和交流
