### ISSUE TITLE
输入框最大最小值数字修改报错

### ISSUE THREAD

**Issue by YoYeJ** [didi/xiaoju-survey#174]
### 分类

前端
### 系统
mac
### 复现步骤

<img width="1429" alt="image" src="https://github.com/didi/xiaoju-survey/assets/62385795/271f5713-0bc2-4a29-aabe-9d2e6f5b28cc">
输入框最大最小值数字修改报错
### 预期结果
能正常修改
### 实际结果
修改不了

**Comment by alwayrun** [comment]
此问题确实存在，重构过程中取参数值导致

@sudoooooo

**Comment by alwayrun** [comment]
@YoYeJ 
感谢反馈，已提交 PR， 等待合并后更新代码此问题解决！

**Comment by sudoooooo** [comment]
@YoYeJ 感谢反馈，已修复到main分支
