### ISSUE TITLE
切换同种类型题目时，页面上配置项没有及时更新

### ISSUE THREAD

**Issue by YoYeJ** [didi/xiaoju-survey#176]
### 分类

前端
### 系统
mac
### 复现步骤

切换同种类型题目时，页面上配置项没有及时更新
<img width="1414" alt="image" src="https://github.com/didi/xiaoju-survey/assets/62385795/31d1c759-cbf3-4f8d-8a36-d6cd58844026">

### 预期结果
每一个题目切换更新相应的配置项
### 实际结果
同种类型题目切换时props数据更新了，视图没有更新

**Comment by alwayrun** [comment]
此问题确实存在，重构过程中状态监听无效导致

@sudoooooo

**Comment by alwayrun** [comment]
@YoYeJ 

感谢反馈，已提交 PR， 等待合并后更新代码此问题解决！

**Comment by sudoooooo** [comment]
@YoYeJ 感谢反馈，已修复到main分支
