### ISSUE TITLE
题型属性-显示序号

### ISSUE THREAD

**Issue by alwayrun** [didi/xiaoju-survey#183]
目前我看系统中针对每个题型都有一个 _显示序号_ 的属性设置，是否有这种特别的场景需要对某些题型设置成显示或隐藏序号，如果没有这种部分题型单独设置 _显示序号_ 的要求，这个属性设置是否归类到问卷级更合理，正常情况 _显示序号_ 应该是针对整份问卷所有题目的，如果按现在设计放在题型级属性设置上，配置一份问卷隐藏 _显示序号_  需要对整份问卷所有题型都进行设置，这样增加了配置问卷交互操作次数

**Comment by ywfyyds** [comment]
有些场景中，会把其中一道题目设置不显示序号，仅作为判断条件。例如第一题让用户选择所在城市，第一题是不显示序号的，仅作为表单中的一个前置项，从第二题开始才显示序号，主观上会让答题者感觉答的题目少一些，其他类似场景也一样。
此外，在全局显示序号这个功能确实是一种快捷操作方式，我们已经实现了，只是在开源项目中还未加入。但并不意味着有了全局显示序号，单题的设置功能就可以取消了。可以理解为，绝大多数B端系统，即便有了全选勾选、全部删除，也仍然会保留单个勾选、单个删除。这种设置既是为了覆盖更全的用户场景，也是为了保持产品设计的统一性。

**Comment by alwayrun** [comment]
> 有些场景中，会把其中一道题目设置不显示序号，仅作为判断条件： 例如第一题让用户选择所在城市，第一题是不显示序号的，仅作为表单中的一个前置项，从第二题开始才显示序号，主观上会让答题者感觉答的题目少一些，其他类似场景也一样。 绝大多数B端系统，即便有了全选勾选、全部删除，也仍然会保留单个勾选、单个删除。这种设置既是为了覆盖更全的用户场景，也是为了保持产品设计的统一性。🤝

@ywfyyds 
如果是这样的话 问题级跟题型级都加一个更合理些， 问题级操作相当于 全部显示或全部隐藏， 题型级有设置则覆盖问卷级的

**Comment by ywfyyds** [comment]
好的，我已经收到了你的邮件。

**Comment by sudoooooo** [comment]
已经收录到官方Featrue：
https://github.com/didi/xiaoju-survey/issues/45 - 全局配置：全部必填、全部显示类型、全部显示序号、全部显示分割线

**Comment by sudoooooo** [comment]
> 已经收录到官方Featrue： #45 - 全局配置：全部必填、全部显示类型、全部显示序号、全部显示分割线

@alwayrun 已完成：https://github.com/didi/xiaoju-survey/issues/45 的8月Feature，issue先关闭了，感谢更多的反馈和交流。

**Comment by ywfyyds** [comment]
好的，我已经收到了你的邮件。
