### ISSUE TITLE
问卷编辑-题型拖拽问题

### ISSUE THREAD

**Issue by alwayrun** [didi/xiaoju-survey#185]
### 分类
前端

### 系统
mac

### 复现步骤
1、当前问卷有三个题目如下图
<img width="1175" alt="image" src="https://github.com/didi/xiaoju-survey/assets/558808/bacebcfc-c2fe-44d3-9785-91d177154cd6">

2、选中当前问卷第一题，按住右侧操作栏移动图标往第二题后拖动
<img width="1159" alt="image" src="https://github.com/didi/xiaoju-survey/assets/558808/a6ced669-1cc1-48ed-8492-4a931a9627c2">

3、拖动到目的地后放开拖动按钮则会回弹到原来题型所有位置
<img width="1204" alt="image" src="https://github.com/didi/xiaoju-survey/assets/558808/8fb73ac4-ed3b-4745-a1bf-484be64733a5">

### 预期结果
两种情况：
1、从前往后拖，拖动到某一目标题型后，目标题型处之前全往前移
2、从后往前拖，拖动到某一目标题型前，目标题型处之后全往后移

**Comment by sudoooooo** [comment]
@alwayrun 🤝 已合并 https://github.com/didi/xiaoju-survey/commit/ea342a0d0b2b489206cc28bd3dc85c4350c725b3
