### ISSUE TITLE
问卷编辑-题型上下移动选区未移动问题

### ISSUE THREAD

**Issue by alwayrun** [didi/xiaoju-survey#186]
### 分类
前端

### 系统
mac
### 复现步骤
1、当题型处于活动态时，使用右侧操作栏 上移或下移 操作移动当前题型，活动态选区没跟着题型移动
<img width="1225" alt="image" src="https://github.com/didi/xiaoju-survey/assets/558808/cf122f5b-3124-43cc-83ed-dbb0414bce86">

2、题型已移动、活动选区还在之前位置
<img width="1197" alt="image" src="https://github.com/didi/xiaoju-survey/assets/558808/5c119127-098e-40ed-8058-3ce4d8c2ab3e">

### 预期结果
当活动态题型移动位置时，活动选区跟着题型走

**Comment by sudoooooo** [comment]
@alwayrun 🤝 已合并 https://github.com/didi/xiaoju-survey/commit/1bd2968982eae6629c3ce9f47de64c3b445d2b03
