### ISSUE TITLE
有个小问题，为什么没有用Vue3呢

### ISSUE THREAD

**Issue by zepingwong** [didi/xiaoju-survey#21]

**Comment by sudoooooo** [comment]
您好，项目使用vue2.7主要作为从vue2到vue3的过渡版本，这一版本保留了vue2版本的原始特性，同时增加了部分vue3的写法的特性。
主要考虑对熟悉vue2或者vue3版本的同学都容易上手，如果比较习惯vue3中更符合函数式编程范式的composition-api的写法，是完全可以再项目中使用的，项目中关于题型物料的代码正是使用composition-api的写法。

ps：
后续我们也会考虑出vue3版本，或vue3版本交由社区维护。
如果您对vue2和vue3中不同的编程写法感兴趣或者想参与共同建设，欢迎一起交流讨论~
