### ISSUE TITLE
能删除在逻辑设置中的题目

### ISSUE THREAD

**Issue by xixiIBN5100** [didi/xiaoju-survey#250]
### 分类

前端
### 系统
mac
### 复现步骤

在逻辑最后一空选中题目
<img width="1078" alt="截屏2024-05-30 17 41 50" src="https://github.com/didi/xiaoju-survey/assets/144224541/8c6c043f-c272-4484-805c-c6adcf3f32cb">
删除题目
<img width="746" alt="截屏2024-05-30 17 42 01" src="https://github.com/didi/xiaoju-survey/assets/144224541/9e092653-3d1a-4b39-b2f8-b4231a28004e">

### 预期结果
不能被删除或者删除时input内容被清空
### 实际结果
<img width="903" alt="截屏2024-05-30 17 42 16" src="https://github.com/didi/xiaoju-survey/assets/144224541/7b48326c-27af-486a-97dc-c3e13233a37f">

**Comment by alwayrun** [comment]
感觉删除时关联条件也去掉更合理些

**Comment by sudoooooo** [comment]
@xixiIBN5100 已收录进优化： https://github.com/didi/xiaoju-survey/issues/182 第9项

**Comment by sudoooooo** [comment]
> 感觉删除时关联条件也去掉更合理些

体验上可以做删除拦截校验

**Comment by sudoooooo** [comment]
已收录进优化： https://github.com/didi/xiaoju-survey/issues/182 第9项，欢迎大家认领

**Comment by sudoooooo** [comment]
> 已收录进优化： #182 第9项，欢迎大家认领

@xixiIBN5100 已完成优化：https://github.com/didi/xiaoju-survey/issues/182 第9项，关闭issue，欢迎更多交流和反馈 🤝
