### ISSUE TITLE
物料基础组件 BaseRate 重复触发 change 事件问题

### ISSUE THREAD

**Issue by alwayrun** [didi/xiaoju-survey#253]
### 分类
 前端

### 系统
Mac

### 复现步骤
<img width="1426" alt="image" src="https://github.com/didi/xiaoju-survey/assets/558808/70ca491c-4209-45b5-be69-0fb123465333">

### 预期结果
未选中变为已选中触发 change 事件， 已选中再次点击不应该触发 change 事件

**Comment by sudoooooo** [comment]
@alwayrun 🤝 已合并：https://github.com/didi/xiaoju-survey/commit/e2e82dc3f3fc09552a61a29b6ee89baeaec53ccc
