### ISSUE TITLE
windows10服务端执行 npm run local 报错

### ISSUE THREAD

**Issue by Realabiha** [didi/xiaoju-survey#29]
分类：后端
类别：Bug
系统: windows10
node版本: 16.16.0
问题：进入server目录，安装依赖之后，执行npm run local报错，报错如图

![微信图片_20231219012246](https://github.com/didi/xiaoju-survey/assets/48506355/95663e4d-51b4-4b20-9766-17236869f8ca)

**Comment by luch1994** [comment]
根据提示，是因为你电脑缺少 Visual C++ Redistributable Packages，这个是一个Visual C++ 的运行库，你可以点击报错提示里面的链接： https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170    下载最新的安装包，安装后重试

![image](https://github.com/didi/xiaoju-survey/assets/32321690/5bafb413-75ef-48e2-9935-bfa1f4465168)


为什么需要这个Visual C++ 运行库？是因为当使用 npm run local 启动服务的时候，会使用mongodb-memory-server在内存里启动一个临时的mongo服务，启动mongo服务的时候依赖了Visual C++ 运行库
