### ISSUE TITLE
C端答题验证

### ISSUE THREAD

**Issue by q1461561** [didi/xiaoju-survey#298]
### 描述您考虑过的备选方案 / 建议
希望有一个后端接入收到表单短信提醒或者公众号等功能 。前端填写问卷手机号短信验证

**Comment by sudoooooo** [comment]
@q1461561 请补充一下应用场景是什么呢？看描述简单理解是用于C端答题验证吗？

**Comment by q1461561** [comment]
是的 C端&nbsp; 答题验证 ， 以免有些乱填写，这样采集更加有效，更好的剔除无限&nbsp; &nbsp;如有问题也可以及时的和客户电话联系 后端需要一个短信或者公众号接口 有收到填写的表单时可以及看到



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月17日(星期一) 上午10:15
收件人: ***@***.***&gt;; 
抄送: "/炮炮兵歪脖    ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [didi/xiaoju-survey] 需求 (Issue #298)














 
@q1461561 请补充一下应用场景是什么呢？看描述简单理解是用于C端答题验证吗？

**Comment by sudoooooo** [comment]
> 是的 C端&nbsp; 答题验证 ， 以免有些乱填写，这样采集更加有效，更好的剔除无限&nbsp; &nbsp;如有问题也可以及时的和客户电话联系 后端需要一个短信或者公众号接口 有收到填写的表单时可以及看到
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年6月17日(星期一) 上午10:15 收件人: ***@***.***&gt;; 抄送: "/炮炮兵歪脖 ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [didi/xiaoju-survey] 需求 (Issue #298) @q1461561 请补充一下应用场景是什么呢？看描述简单理解是用于C端答题验证吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

C端白名单管理已是一个Feature在建设：我们会增加密码、白名单（手机号、邮箱、自定义名单）这两部分内容。
由于我们主要围绕高扩展的技术架构和基础化的产品功能性进行整个生态的建设，等这个feature发布后，可自行灵活扩展短信验证码的能力。其实已经比较类似了。

**Comment by q1461561** [comment]
好的， 大概多久会 发布出来



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月17日(星期一) 下午4:20
收件人: ***@***.***&gt;; 
抄送: "/炮炮兵歪脖    ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [didi/xiaoju-survey] 需求 (Issue #298)














  
是的 C端&nbsp; 答题验证 ， 以免有些乱填写，这样采集更加有效，更好的剔除无限&nbsp; &nbsp;如有问题也可以及时的和客户电话联系 后端需要一个短信或者公众号接口 有收到填写的表单时可以及看到
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年6月17日(星期一) 上午10:15 收件人: @.&gt;; 抄送: "/炮炮兵歪脖 @.&gt;; @.&gt;; 主题: Re: [didi/xiaoju-survey] 需求 (Issue #298) @q1461561 请补充一下应用场景是什么呢？看描述简单理解是用于C端答题验证吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
@q1461561  感谢交流🤝。
 C端白名单管理已是一个Feature在建设：我们会增加密码、白名单（手机号、邮箱、自定义名单）这两部分内容。
 由于我们主要围绕高扩展的技术架构和基础化的产品功能性进行整个生态的建设，等这个feature发布后，可自行灵活扩展短信验证码的能力。其实已经比较类似了。

**Comment by sudoooooo** [comment]
> 好的， 大概多久会 发布出来
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年6月17日(星期一) 下午4:20 收件人: ***@***.***&gt;; 抄送: "/炮炮兵歪脖 ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [didi/xiaoju-survey] 需求 (Issue #298) 是的 C端&nbsp; 答题验证 ， 以免有些乱填写，这样采集更加有效，更好的剔除无限&nbsp; &nbsp;如有问题也可以及时的和客户电话联系 后端需要一个短信或者公众号接口 有收到填写的表单时可以及看到 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年6月17日(星期一) 上午10:15 收件人: @.&gt;; 抄送: "/炮炮兵歪脖 @.&gt;; @.&gt;; 主题: Re: [didi/xiaoju-survey] 需求 (Issue #298) @q1461561 请补充一下应用场景是什么呢？看描述简单理解是用于C端答题验证吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt; @q1461561 感谢交流🤝。 C端白名单管理已是一个Feature在建设：我们会增加密码、白名单（手机号、邮箱、自定义名单）这两部分内容。 由于我们主要围绕高扩展的技术架构和基础化的产品功能性进行整个生态的建设，等这个feature发布后，可自行灵活扩展短信验证码的能力。其实已经比较类似了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

@q1461561 您好，答卷白名单配置已经在main分支
