### ISSUE TITLE
[refactor]: check for the ispc-html class is done using a regular expression to ensure that the class is only added once when the browser window is resized

### ISSUE THREAD

**Issue by yelang-web** [didi/xiaoju-survey#299]
### 您的需求是否与某个问题有关？
pc端填写问卷页面浏览器resize后 html标签会有多个ispc-html类名

### 描述您希望的需求
pc端填写问卷页面浏览器resize后 html标签只保留一个 ispc-html类名

### 描述您考虑过的备选方案 / 建议
优化添加类名代码

### 我想要认领此需求 / 优化
确认认领，预计可完成时间为一天内

**Comment by sudoooooo** [comment]
@yelang-web 👍已接收PR：https://github.com/didi/xiaoju-survey/commit/97532152819c718abf441e4e003b201ef4f680b5

**Comment by sudoooooo** [comment]
@yelang-web 感谢反馈和建设，PR已合并到main分支。此先issue关闭了，欢迎更多的反馈和共建🤝。
