### ISSUE TITLE
希望在前端页面支持导出

### ISSUE THREAD

**Issue by mengnimen** [didi/xiaoju-survey#30]
在数据统计-数据列表，增加数据部分、全部导出功能，支持excel便于统计。

**Comment by mengnimen** [comment]
问卷列表页面增加删除功能，现在只能增加

**Comment by sudoooooo** [comment]
> 问卷列表页面增加删除功能，现在只能增加

您好，列表有删除功能
![clipboard_image_1704176776085](https://github.com/didi/xiaoju-survey/assets/16012672/ec749c69-1c63-440a-8370-ed277bd5e91e)

**Comment by mengnimen** [comment]
我看docker镜像已经到了1.0.1了 我更新试试。

**Comment by mengnimen** [comment]
<img width="1465" alt="iShot_2024-01-02_17 35 17" src="https://github.com/didi/xiaoju-survey/assets/105690750/23a23d21-ee62-482b-aecd-36f8b4769c06">
docker1.0.1版本还是没有的

**Comment by sudoooooo** [comment]
> <img alt="iShot_2024-01-02_17 35 17" width="1465" src="https://private-user-images.githubusercontent.com/105690750/293662992-23a23d21-ee62-482b-aecd-36f8b4769c06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNTcxNzUsIm5iZiI6MTcwNDM1Njg3NSwicGF0aCI6Ii8xMDU2OTA3NTAvMjkzNjYyOTkyLTIzYTIzZDIxLWVlNjItNDgyYi1hZWNkLTM2ZjhiNDc2OWMwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQwODI3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjhiZTg5MmQ1ODdiZGZmNTY1OGIwODQ3NzhmYzUzNDY2Y2VjNGFmODlkYmI3YTNlNjBiYzY0YzU3OTQwZjE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q-OkANsGfreIsuEVLl6m8ba_ED5xeUqybFrqbyTqtfw"> docker1.0.1版本还是没有的

您好，1.0.2版本已同步更新

**Comment by sudoooooo** [comment]
> <img alt="iShot_2024-01-02_17 35 17" width="1465" src="https://private-user-images.githubusercontent.com/105690750/293662992-23a23d21-ee62-482b-aecd-36f8b4769c06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNTcyNDEsIm5iZiI6MTcwNDM1Njk0MSwicGF0aCI6Ii8xMDU2OTA3NTAvMjkzNjYyOTkyLTIzYTIzZDIxLWVlNjItNDgyYi1hZWNkLTM2ZjhiNDc2OWMwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQwODI5MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjM3ZTc4MTI1MjA1NmE2ZGU4YTVmYzE2NGJjMWUxNmYzYTlhMzQ0OThjNTgxYjZmM2Q4YTMzYmQ2MDJiZmVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XbK1B3NC8cZ3AZgS0yy0PsDL4D8mOWRpXOUrPxZUkFA"> docker1.0.1版本还是没有的

@mengnimen 您好，1.0.2版本已同步更新

**Comment by sudoooooo** [comment]
@mengnimen 您好，导出功能已支持并发布main分支和docker1.2.0。
[查看介绍](https://xiaojusurvey.didi.cn/docs/next/document/%E4%BA%A7%E5%93%81%E6%89%8B%E5%86%8C/%E5%8A%9F%E8%83%BD%E4%BB%8B%E7%BB%8D/%E5%9F%BA%E7%A1%80%E6%B5%81%E7%A8%8B#%E5%AF%BC%E5%87%BA)

issue先关闭了，欢迎更多交流🤝。
