### ISSUE TITLE
Pinia迁移认领：vuex迁移到pinia

### ISSUE THREAD

**Issue by sudoooooo** [didi/xiaoju-survey#308]
本次迁移源自vue3升级的后续：https://github.com/didi/xiaoju-survey/issues/108
如疑问，请听官方解释(jiaobian)： [为什么你应该使用 Pinia？](https://pinia.vuejs.org/zh/introduction.html#why-should-i-use-pinia)

如果你想熟悉工程和pinia用法，或者参与贡献，这是一个比较好的机会。

## 认领方式
> 为保障正常建设，认领1个月内无响应(沟通讨论/技术方案/PR)，任务自动释放

1、留言认领：模块或者模块-功能点 + 预计完成时间
2、官方会将跟进人标记到此Issue等于认领成功
3、基于**feature/pinia**分支，改造后通过以下检测：
        vscode无飘红（安装插件：[Vue - Official](https://cn.vuejs.org/guide/scaling-up/tooling.html#ide-support) 和 Eslint）
        npm run format
        npm run lint
        相关功能自测通过
4、提交PR到**feature/pinia**分支

### 说明
1、由原来的 `store` 放到 `stores` 目录
2、[迁移指南](https://pinia.vuejs.org/zh/cookbook/migration-vuex.html)
3、[pinia推荐迁移成setup的风格](https://pinia.vuejs.org/zh/cookbook/composables.html#setup-stores)
> 为什么用setup风格？
> 从代码风格统一：开源工程的代码风格基本采用了vue3的setup风格
> 组合式写法相比选项式写法能够检测到未被使用的函数
> 值得一提的是, 当我们定义一个 setup store 时，几乎可以使用任何组合式函数，因为每一个属性都会被> 自动被辨别为 state 、action 或者 getter，而不需要采用options Store的方案显示的声明，具体使用方式可参考下面的迁移示例

4、示例：[user模块迁移案例](https://github.com/didi/xiaoju-survey/commit/cdd26073afd1f34f8cdfcb2c54ecc27673ea4971#diff-1bd608343482e430319755fef19500fc92c13e5c1bf5bf4deb1d9478c4999996)
5、阶段性会反向合并develop分支，提交PR前关注可能会存在的冲突

## 任务列表
> 为保障正常建设，认领1个月内无响应(沟通讨论/技术方案/PR)，任务自动释放

### B端搭建端
- [x] 1、user用户相关 @skique ，进展：已完成
                userInfo
                hasLogined
                loginTime
                initialized
- [x] 2、edit问卷编辑页相关 @webaddkevin，进展：已完成
                bannerList
                cooperPermissions
                surveyId
                schema
                schemaUpdateTime
                currentEditOne
                currentEditStatus
                moduleConfig（computed）
                formConfigList（computed）
                currentEditMeta（computed）
                currentEditKey（computed）
- [x] 3、list空间 @whitexie ，进展：已完成
                  spaceMenus
                  spaceType
                  workSpaceId
                  spaceDetail
                  teamSpaceList
- [x] 4、list列表 @whitexie ，进展：已完成
                    surveyList
                    surveyTotal
                    searchVal
                    selectValueMap
                    buttonValueMap
                    listFliter（computed）
                    listOrder（computed）
### C端渲染端
- [x] 1、问卷相关 @yoruponder ，进展：已完成
          surveyPath
          isMobile
          enterTime
          encryptInfo
- [x] 2、答题页相关 @1004801012 ，进展：已完成
          questionData
          questionSeq
          renderData（computed）
          voteMap
- [x] 3、错误页相关 @yoruponder ，进展：已完成
          errorInfo

（若有遗漏欢迎进行补充）

- [x] 4、问卷相关的遗漏补充 @whitexie ，进展：已完成
        rules
        bannerConf
        baseConf
        bottomConf
        dataConf
        skinConf
        submitConf
        formValues

**Comment by yoruponder** [comment]
@sudoooooo 你好，认领C端这个可以吗？

1、问卷相关
surveyPath
isMobile
enterTime
encryptInfo

**Comment by sudoooooo** [comment]
> @sudoooooo 你好，认领C端这个可以吗？
> 
> 1、问卷相关 surveyPath isMobile enterTime encryptInfo

确认认领，已记录

**Comment by 1004801012** [comment]
认领
2、答题页相关
questionData
questionSeq
renderData（computed）
voteMap

**Comment by sudoooooo** [comment]
> 认领 2、答题页相关 questionData questionSeq renderData（computed） voteMap

@1004801012 确认认领，已记录

**Comment by whitexie** [comment]
认领：
3、list空间
spaceMenus
spaceType
workSpaceId
spaceDetail
teamSpaceList
 4、list列表
surveyList
surveyTotal
searchVal
selectValueMap
buttonValueMap
listFliter（computed）
listOrder（computed）

**Comment by sudoooooo** [comment]
> 确认认领，已记录

@whitexie 确认认领，已记录

**Comment by webaddkevin** [comment]
认领edit问卷编辑页相关

**Comment by sudoooooo** [comment]
> 确认认领，已记录

@webaddkevin 确认认领，已记录

**Comment by yoruponder** [comment]
你好，认领
 3、错误页相关
errorInfo

**Comment by sudoooooo** [comment]
> 你好，认领 3、错误页相关 errorInfo

@yoruponder 确认认领，已记录

**Comment by sudoooooo** [comment]
> 你好，认领 3、错误页相关 errorInfo

@yoruponder 你好，有个认领feature的用户需要基于迁移版本进行开发。目前只剩下erroInfo就可以全部迁移完成，请问方便先提个PR吗？

**Comment by yoruponder** [comment]
@sudoooooo 大佬好的，今晚搞下提PR，最近这几周工作上业务需求太多了，不好意思了

**Comment by sudoooooo** [comment]
> @sudoooooo 大佬好的，今晚搞下提PR，最近这几周工作上业务需求太多了，不好意思了

@yoruponder 非常感谢理解

**Comment by sudoooooo** [comment]
补充了部分遗漏的内容，有哪位朋友感兴趣认领吗？

**Comment by whitexie** [comment]
认领：
问卷相关的遗漏补充
rules
bannerConf
baseConf
bottomConf
dataConf
skinConf
submitConf
formValues
