### ISSUE TITLE
加题目问题

### ISSUE THREAD

**Issue by chart00** [didi/xiaoju-survey#358]
### 分类

前端
### 复现步骤

https://github.com/user-attachments/assets/ddf7c576-03c5-4a35-955f-d6d6c50e7e07

### 实际结果
新增同类题目设置的值不变

**Comment by sudoooooo** [comment]
@chart00 感谢反馈，已解决：https://github.com/didi/xiaoju-survey/commit/6c396c6ec8a4833858182f962094692cb09db74f
