### ISSUE TITLE
希望增加跳题逻辑

### ISSUE THREAD

**Issue by alwayrun** [didi/xiaoju-survey#36]
希望增加跳题逻辑，例如在有些情况下，输入题输入了某个值或选择题选了某可以跳过(或隐藏)中间一些题不做

<img width="925" alt="image" src="https://github.com/didi/xiaoju-survey/assets/558808/38709718-6da4-42d9-b567-dd43a3e0a10c">

**Comment by sudoooooo** [comment]
@alwayrun 显示逻辑已建设：https://github.com/didi/xiaoju-survey/commit/142b3b7be97b8b646f3e52a0e496b3adcc2794af
跳转逻辑录入六月feature：可关注 https://github.com/didi/xiaoju-survey/issues/45

**Comment by sudoooooo** [comment]
@alwayrun 跳转逻辑已建设：https://github.com/didi/xiaoju-survey/commit/c3f8b2a938476ca547a9cae964d288a90a7ed117
docker：1.1.9

🤝 issue关闭了～
