### ISSUE TITLE
题目未聚焦时拖拽按钮失效

### ISSUE THREAD

**Issue by xixiIBN5100** [didi/xiaoju-survey#363]
### 分类

前端
### 复现步骤

<img width="2560" alt="image" src="https://github.com/user-attachments/assets/0d3688b2-fd4c-494d-842c-b94dc0b52332">
题目未聚焦时拖拽按钮失效

### 预期结果

实现拖拽题目

### 实际结果

拖拽失效

**Comment by sudoooooo** [comment]
@xixiIBN5100 感谢反馈，已修复https://github.com/didi/xiaoju-survey/commit/0745d90a5cbef76866aa50a34e80141b1f7a33eb
issue先关闭了，欢迎提交更多反馈🤝
