### ISSUE TITLE
短标题hover空白处会触发指示框

### ISSUE THREAD

**Issue by xixiIBN5100** [didi/xiaoju-survey#364]
### 分类

前端
### 系统
mac
### 复现步骤

<img width="1439" alt="image" src="https://github.com/user-attachments/assets/2b737f85-c7a7-4fbf-b52a-d8e6b42e0aa6">

### 预期结果
不显示
### 实际结果
显示指示框

**Comment by sudoooooo** [comment]
@xixiIBN5100 已合并：https://github.com/didi/xiaoju-survey/commit/15d93abea3c2a36d5ce4c654277a9d224ea812cf
