### ISSUE TITLE
docker部署完后登录的admin密码去哪里找？

### ISSUE THREAD

**Issue by ivanmissu** [didi/xiaoju-survey#457]
RT

**Comment by ivanmissu** [comment]
好像不是这个问题，是docker部署完，登录接口是500。  可以注册  但是不提示，

**Comment by sudoooooo** [comment]
> 好像不是这个问题，是docker部署完，登录接口是500。 可以注册 但是不提示，

发一下环境和复现步骤。

**Comment by wvqkhn** [comment]
![image](https://github.com/user-attachments/assets/0e3620f4-6ef8-44b3-9a8f-57a229872539)
 登陆和注册都有这个问题

**Comment by brign123** [comment]
我也碰到了这个问题，是 docker compose 部署的。
`secretOrPrivateKey must have a value`
这个 `secretOrPrivateKey` 在哪设置？

**Comment by sudoooooo** [comment]
> 我也碰到了这个问题，是 docker compose 部署的。 `secretOrPrivateKey must have a value` 这个 `secretOrPrivateKey` 在哪设置？

@wvqkhn @brign123 
这个问题我们已经排查根因是因为这一版的镜像缺少.env.production环境变量，导致用户注册后生成密钥失败。
main分支最新的代码已经修复；1.3.1版本的镜像也已修复。

**Comment by sudoooooo** [comment]
@ivanmissu 请问问题解决了吗？

**Comment by ivanmissu** [comment]
> @ivanmissu 请问问题解决了吗？

解决了  thanks

**Comment by ivanmissu** [comment]
> @ivanmissu 请问问题解决了吗？

已经解决 thanks
