### ISSUE TITLE
评分组件高级设置显示异常

### ISSUE THREAD

**Issue by chaorenluo** [didi/xiaoju-survey#62]
- 分类：前端
- 类别：Bug
- 标题： 评分组件高级设置显示异常
- 操作系统： Mac
- 内容：点击评分组件高级设置修改，修改完成后再次点击高级设置，之前修改的内容消失
- 操作步骤：点击评分组件高级设置修改，修改完成后再次点击高级设置，之前修改的内容消失
- 期待的行为：修改后再次点击能看到修改的内容
- 实际行为：看不到之前修改的内容
- 
<img width="821" alt="image" src="https://github.com/didi/xiaoju-survey/assets/27545556/2dbd4a06-c8b9-4f1d-9690-a508df7231ac">

<img width="983" alt="image" src="https://github.com/didi/xiaoju-survey/assets/27545556/107e1623-ad4a-4ecd-b9f1-d6b89a39c283">

**Comment by chaorenluo** [comment]
问题原因：
<img width="1296" alt="image" src="https://github.com/didi/xiaoju-survey/assets/27545556/5003eba2-8cd9-423e-96d7-133371f664de">
inject 获取到的moduleConfig数据不带响应式导致再次点击看不到修改过的数据

解决方案：通过计算属性获取moduleConfig然后通过props传递使其具有响应式
<img width="1263" alt="image" src="https://github.com/didi/xiaoju-survey/assets/27545556/9c158570-5df9-456a-8176-a281069c9ce2">
<img width="1087" alt="image" src="https://github.com/didi/xiaoju-survey/assets/27545556/ae4bed0e-d0a8-4c37-8da9-cecdc59c17fb">
<img width="1081" alt="image" src="https://github.com/didi/xiaoju-survey/assets/27545556/2fbca0ec-bcac-486b-89d2-8e366a174b39">

**Comment by skique** [comment]
非常感谢您的试用，并且发现一些程序运行中的问题，您的提供的解决方案确实是一种有效的途径，但是这个缺陷的根因我想补充修正一下：父级组件提供的moduleConfig不是一个响应式的数据对象，导致inject 获取到的moduleConfig数据失去了响应式，那么解决方案调整为provide提供一个响应式的数据更加合理呢？
<img width="612" alt="image-20240223213813411" src="https://github.com/didi/xiaoju-survey/assets/17895803/cf42be14-1c4d-4636-a96c-5ae83d4a7660">

**Comment by sudoooooo** [comment]
> 问题原因： <img alt="image" width="1296" src="https://private-user-images.githubusercontent.com/27545556/306943148-5003eba2-8cd9-423e-96d7-133371f664de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTMwNjUsIm5iZiI6MTcwODc1Mjc2NSwicGF0aCI6Ii8yNzU0NTU1Ni8zMDY5NDMxNDgtNTAwM2ViYTItOGNkOS00MjNlLTk2ZDctMTMzMzcxZjY2NGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA1MzI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0OTIwMGQxZDNiNzNiMDJjOGI0ZmNlZmE4YWIyNWUwNWQwZmIzNTEzOGJlYTZjNWU5MTc5OGZlYzBmNGMxMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PpqAao4j_TElw-R2X3BiSVQ5zqCWEt7ekHbWZ8WA_BU"> inject 获取到的moduleConfig数据不带响应式导致再次点击看不到修改过的数据
> 
> 解决方案：通过计算属性获取moduleConfig然后通过props传递使其具有响应式 <img alt="image" width="1263" src="https://private-user-images.githubusercontent.com/27545556/306943572-9c158570-5df9-456a-8176-a281069c9ce2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTMwNjUsIm5iZiI6MTcwODc1Mjc2NSwicGF0aCI6Ii8yNzU0NTU1Ni8zMDY5NDM1NzItOWMxNTg1NzAtNWRmOS00NTZhLTgxNzYtYTI4MTA2OWM5Y2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA1MzI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxYWNiNmYwNWQwNDY1YjgyN2E4NTllZGU2OTFhMDcyMWRjMTY4YmI1ZjkzNWVhODdmYmU0OGRjYzJhYjYyZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5j45hJKe65LHr8JgvjC67gIVg0hte1Qs0lk27gjHfHg"> <img alt="image" width="1087" src="https://private-user-images.githubusercontent.com/27545556/306943652-ae4bed0e-d0a8-4c37-8da9-cecdc59c17fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTMwNjUsIm5iZiI6MTcwODc1Mjc2NSwicGF0aCI6Ii8yNzU0NTU1Ni8zMDY5NDM2NTItYWU0YmVkMGUtZDBhOC00YzM3LThkYTktY2VjZGM1OWMxN2ZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA1MzI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYzgwOGY1NTg3NWM2ODkwMDA0NTQwOTEyYzJkNTY2ZTRkYjllOWE1MTg1OThmZDhjNmI0NzkwODk5YzBmNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zubKMRLeGvZtZOBkyX-84mPw-Olgo35wziDlXYcyt9A"> <img alt="image" width="1081" src="https://private-user-images.githubusercontent.com/27545556/306943730-2fbca0ec-bcac-486b-89d2-8e366a174b39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTMwNjUsIm5iZiI6MTcwODc1Mjc2NSwicGF0aCI6Ii8yNzU0NTU1Ni8zMDY5NDM3MzAtMmZiY2EwZWMtYmNhYy00ODZiLTg5ZDItOGUzNjZhMTc0YjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA1MzI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNjAxOTdjYWU3Zjc2NWJiMDBlOTA3M2MwNjM4NWYyZGI5NjU1NjUxY2JlMGUyZDgyOTVlNTRlY2FjZGQ1MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SoIQehSstqC176F6-UItaGT9T8qG-TdtsOBFdBNW-A8">

**Comment by chaorenluo** [comment]
> @chaorenluo非常感谢您的使用，并且发现一些程序运行中的问题，您提供的解决方案确实是一种有效的实现组件，但仍然需要在EditOptions下的所有子组件获取数据，且不受组件嵌合所以可优化方案如下： 这里的根源是父级组件提供的moduleConfig不是一个响应式的数据对象，导致注入获取到的moduleConfig失去了响应式，那么解决方案调整为提供一个响应式响应式的数据，这样从数据的上游解决问题更加彻底 <img alt="图片-20240223213813411" width="612" src="https://private-user-images.githubusercontent.com/17895803/307338852-cf42be14-1c4d-4636-a96c-5ae83d4a7660.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwODI3MTQsIm5iZiI6MTcwOTA4MjQxNCwicGF0aCI6Ii8xNzg5NTgwMy8zMDczMzg4NTItY2Y0MmJlMTQtMWM0ZC00NjM2LWE5NmMtNWFlODNkNGE3NjYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDAxMDY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MDViYmFkYTYxNDQyYzdjZjkyYzUwM2I4ZGZjODdjZWMwNjI1NjBkNjAxZDgzNTgwMjI4Y2U3ZmNhOWZkM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ptXNlbbnBqGeE2l39L5piz_PRMQ4FkJuB5FaoBqBU9M">

好的我修改后再次提交

**Comment by chaorenluo** [comment]
@skique 非常感谢您的建议现在我将修改为
<img width="897" alt="image" src="https://github.com/didi/xiaoju-survey/assets/27545556/0ae06611-b628-4f6a-b318-2e19b653fec8">
在provide
