### ISSUE TITLE
missing babel-loader pakcgae

### ISSUE THREAD

**Issue by busyhe** [didi/xiaoju-survey#72]
ERROR in management
Module not found: Error: Can't resolve 'babel-loader' in '/Users/busyhe/Workspace/projects/xiaoju-survey/web'

ERROR in render
Module not found: Error: Can't resolve 'babel-loader' in '/Users/busyhe/Workspace/projects/xiaoju-survey/web'

**Comment by busyhe** [comment]
and lodash、async-validator

**Comment by skique** [comment]
非常感谢您的反馈，

**Comment by skique** [comment]
你好项目依赖中声明@vue/cli-plugin-babel包，而babel-loader是@vue/cli-plugin-babel的依赖。
![image](https://github.com/didi/xiaoju-survey/assets/17895803/a20adfde-b090-49ae-8fb8-5907437510d8)
您需要检查一下依赖安装好环节的@vue/cli-plugin-babel有没有安装成功，如果还是无法解决需要您进一步提供一下您的node版本以及安装依赖的命令以及启动方式

**Comment by busyhe** [comment]
System:
    OS: macOS 13.6.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 152.06 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    Yarn: 3.6.1 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.15.1 - /usr/local/bin/pnpm

cd web & pnpm install

**Comment by skique** [comment]
pnpm的安装机制在默认情况下不会安装依赖包的依赖，建议使用`pnpm install --shamefully-flatten`命令安装依赖
