### ISSUE TITLE
希望VUE3版本不要过度设计

### ISSUE THREAD

**Issue by zjpzjp** [didi/xiaoju-survey#97]
当前VUE2版本前端设计过于臃肿
前端二开理解难度极大
希望使用标准开发结构，让更多人容易上手，从而贡献项目

**Comment by sudoooooo** [comment]
> 当前VUE2版本前端设计过于臃肿 前端二开理解难度极大 希望使用标准开发结构，让更多人容易上手，从而贡献项目

感谢，请问是否可以列一下具体的建议点和目前较难理解的点呢？

**Comment by zjpzjp** [comment]
以下为个人见解：

1. 层级较深 初次接触不容易理解整体设计思路
- pages
  - analysis
  - create
  - edit
    - components
    - modules
      - questionModule
        - components
    - pages
  - ....
```
建议
1、通过命名减少层级
例如edit的modules可以命名为
edit-question
edit-content
edit-setting
```

2. 直接写出template而不是通过配置循环
例如编辑中的setting,整个项目中并没有复用的可能性，没必要封装
```web\src\management\pages\edit\modules\settingModule```
例如当我想新增一个字段```price``` 我需要连续修改 ```baseConfig.js``` 以及 ```baseFormConfig.js```
而且其中需要用户指定一些“魔术字符串”,这会增加心智负担😄

**Comment by sudoooooo** [comment]
> 以下为个人见解：
> 
> 1. 层级较深 初次接触不容易理解整体设计思路
> 
> * pages
>   
>   * analysis
>   * create
>   * edit
>     
>     * components
>     * modules
>       
>       * questionModule
>         
>         * components
>     * pages
>   * ....
> 
> ```
> 建议
> 1、通过命名减少层级
> 例如edit的modules可以命名为
> edit-question
> edit-content
> edit-setting
> ```
> 
> 2. 直接写出template而不是通过配置循环
>    例如编辑中的setting,整个项目中并没有复用的可能性，没必要封装
>    `web\src\management\pages\edit\modules\settingModule`
>    例如当我想新增一个字段`price` 我需要连续修改 `baseConfig.js` 以及 `baseFormConfig.js`
>    而且其中需要用户指定一些“魔术字符串”,这会增加心智负担😄

1、这个目录拆分是出于场景复杂后的维护性的考虑：
问卷搭建是最复杂的页面，基于我们内部多种问卷类型和复杂场景的经验，到后面会有很多代码的堆叠，内部是迁移成了独立的微前端工程。
但是开源项目不适合抽成微前端，所以进行了领域化概念的设计，以便于后续场景复杂后进行分类别维护和扩展。
详细文档可查看：[问卷搭建领域化设计](https://xiaojusurvey.didi.cn/docs/next/document/%E8%AE%BE%E8%AE%A1%E5%8E%9F%E7%90%86/%E9%97%AE%E5%8D%B7%E6%90%AD%E5%BB%BA%E9%A2%86%E5%9F%9F%E5%8C%96%E8%AE%BE%E8%AE%A1)

2、配置化管理在做相应的优化，接收建议考虑如何降低复杂性🤝
